services:
  postgres:
    image: postgres:18-alpine
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ecommerce
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=3
      -c max_replication_slots=3
      -c hot_standby=on
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./scripts/init-replication.sh:/docker-entrypoint-initdb.d/init-replication.sh
    networks:
      - dbnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-replica:
    image: postgres:18-alpine
    container_name: db-replica
    user: postgres
    environment:
      - PGPASSWORD=123
    command: >
      sh -c "
      if [ ! -f /var/lib/postgresql/18/docker/PG_VERSION ]; then
        until pg_basebackup -h postgres -U root -D /var/lib/postgresql/18/docker -P -R --wal-method=stream;
        do echo 'waiting for primary...'; sleep 2; done;
      fi &&
      chmod 700 /var/lib/postgresql/18/docker &&
      postgres -c hot_standby=on -D /var/lib/postgresql/18/docker
      "
    ports:
      - "5433:5432"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgreplicadata:/var/lib/postgresql
    networks:
      - dbnet

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafkadata:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 0txLEmydSAuV9kPzLFt4QQ
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

volumes:
  pgdata:
  kafkadata:
  pgreplicadata:

networks:
  dbnet:
    driver: bridge
