// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: address.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO
  addresses (
    id,
    user_id,
    full_name,
    phone,
    province,
    district,
    ward,
    street,
    is_default
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, user_id, full_name, phone, province, district, ward, street, is_default, created_at, updated_at
`

type CreateAddressParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	FullName  string    `json:"full_name"`
	Phone     string    `json:"phone"`
	Province  string    `json:"province"`
	District  string    `json:"district"`
	Ward      string    `json:"ward"`
	Street    string    `json:"street"`
	IsDefault bool      `json:"is_default"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.ID,
		arg.UserID,
		arg.FullName,
		arg.Phone,
		arg.Province,
		arg.District,
		arg.Ward,
		arg.Street,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.Province,
		&i.District,
		&i.Ward,
		&i.Street,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM
  addresses
WHERE
  id = $1
`

func (q *Queries) DeleteAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAddress, id)
	return err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT
  id, user_id, full_name, phone, province, district, ward, street, is_default, created_at, updated_at
FROM
  addresses
WHERE
  id = $1
`

func (q *Queries) GetAddressByID(ctx context.Context, id uuid.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.Province,
		&i.District,
		&i.Ward,
		&i.Street,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddressesByUserID = `-- name: GetAddressesByUserID :one
SELECT
  id, user_id, full_name, phone, province, district, ward, street, is_default, created_at, updated_at
FROM
  addresses
WHERE
  user_id = $1
`

func (q *Queries) GetAddressesByUserID(ctx context.Context, userID uuid.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressesByUserID, userID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.Province,
		&i.District,
		&i.Ward,
		&i.Street,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setDefaultAddress = `-- name: SetDefaultAddress :exec
UPDATE
  addresses
SET
  is_default = false
WHERE
  user_id = $1
`

func (q *Queries) SetDefaultAddress(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setDefaultAddress, userID)
	return err
}

const updateAddressDefault = `-- name: UpdateAddressDefault :exec
UPDATE
  addresses
SET
  is_default = true
WHERE
  id = $1
`

func (q *Queries) UpdateAddressDefault(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAddressDefault, id)
	return err
}
