// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, parent_id, name, slug)
VALUES ($1, $2, $3, $4)
RETURNING id, parent_id, name, slug, created_at
`

type CreateCategoryParams struct {
	ID       uuid.UUID   `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Slug,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getCategories = `-- name: GetCategories :many
SELECT id, parent_id, name, slug, created_at FROM categories
WHERE parent_id IS NULL
ORDER BY name
`

func (q *Queries) GetCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubcategories = `-- name: GetSubcategories :many
SELECT id, parent_id, name, slug, created_at FROM categories
WHERE parent_id = $1
ORDER BY name
`

func (q *Queries) GetSubcategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getSubcategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
