// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MethodType string

const (
	MethodTypeTotp  MethodType = "totp"
	MethodTypeSms   MethodType = "sms"
	MethodTypeEmail MethodType = "email"
)

func (e *MethodType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MethodType(s)
	case string:
		*e = MethodType(s)
	default:
		return fmt.Errorf("unsupported scan type for MethodType: %T", src)
	}
	return nil
}

type NullMethodType struct {
	MethodType MethodType `json:"method_type"`
	Valid      bool       `json:"valid"` // Valid is true if MethodType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMethodType) Scan(value interface{}) error {
	if value == nil {
		ns.MethodType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MethodType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMethodType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MethodType), nil
}

type ProviderType string

const (
	ProviderTypeLocal  ProviderType = "local"
	ProviderTypeGoogle ProviderType = "google"
)

func (e *ProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderType(s)
	case string:
		*e = ProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderType: %T", src)
	}
	return nil
}

type NullProviderType struct {
	ProviderType ProviderType `json:"provider_type"`
	Valid        bool         `json:"valid"` // Valid is true if ProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderType), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusBanned    UserStatus = "banned"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuthSession struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Ip               pgtype.Text        `json:"ip"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	IsRemember       bool               `json:"is_remember"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	FullName  string             `json:"full_name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Status    UserStatus         `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserAuth struct {
	UserID       uuid.UUID          `json:"user_id"`
	Provider     ProviderType       `json:"provider"`
	ProviderID   pgtype.Text        `json:"provider_id"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	IsVerified   bool               `json:"is_verified"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type UserMfa struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Method      MethodType         `json:"method"`
	SecretKey   string             `json:"secret_key"`
	BackupCodes []byte             `json:"backup_codes"`
	IsEnabled   bool               `json:"is_enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
