// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, shop_id, status, total_amount, shipping_full_name, shipping_phone, shipping_province, shipping_district, shipping_ward, shipping_street, created_at, updated_at
`

func (q *Queries) CancelOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopID,
		&i.Status,
		&i.TotalAmount,
		&i.ShippingFullName,
		&i.ShippingPhone,
		&i.ShippingProvince,
		&i.ShippingDistrict,
		&i.ShippingWard,
		&i.ShippingStreet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const confirmOrder = `-- name: ConfirmOrder :one
UPDATE orders SET status = 'confirmed', updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, shop_id, status, total_amount, shipping_full_name, shipping_phone, shipping_province, shipping_district, shipping_ward, shipping_street, created_at, updated_at
`

func (q *Queries) ConfirmOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, confirmOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopID,
		&i.Status,
		&i.TotalAmount,
		&i.ShippingFullName,
		&i.ShippingPhone,
		&i.ShippingProvince,
		&i.ShippingDistrict,
		&i.ShippingWard,
		&i.ShippingStreet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO
  orders (
    id,
    user_id,
    shop_id,
    total_amount,
    shipping_full_name,
    shipping_phone,
    shipping_province,
    shipping_district,
    shipping_ward,
    shipping_street
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
  ) RETURNING id, user_id, shop_id, status, total_amount, shipping_full_name, shipping_phone, shipping_province, shipping_district, shipping_ward, shipping_street, created_at, updated_at
`

type CreateOrderParams struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	ShopID           uuid.UUID      `json:"shop_id"`
	TotalAmount      pgtype.Numeric `json:"total_amount"`
	ShippingFullName string         `json:"shipping_full_name"`
	ShippingPhone    string         `json:"shipping_phone"`
	ShippingProvince string         `json:"shipping_province"`
	ShippingDistrict string         `json:"shipping_district"`
	ShippingWard     string         `json:"shipping_ward"`
	ShippingStreet   string         `json:"shipping_street"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.ShopID,
		arg.TotalAmount,
		arg.ShippingFullName,
		arg.ShippingPhone,
		arg.ShippingProvince,
		arg.ShippingDistrict,
		arg.ShippingWard,
		arg.ShippingStreet,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopID,
		&i.Status,
		&i.TotalAmount,
		&i.ShippingFullName,
		&i.ShippingPhone,
		&i.ShippingProvince,
		&i.ShippingDistrict,
		&i.ShippingWard,
		&i.ShippingStreet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO
  order_items (
    id,
    order_id,
    product_id,
    product_name,
    quantity,
    price
  )
VALUES
  ($1, $2, $3, $4, $5, $6) RETURNING id, order_id, product_id, product_name, quantity, price, created_at, updated_at
`

type CreateOrderItemParams struct {
	ID          uuid.UUID      `json:"id"`
	OrderID     uuid.UUID      `json:"order_id"`
	ProductID   uuid.UUID      `json:"product_id"`
	ProductName string         `json:"product_name"`
	Quantity    int32          `json:"quantity"`
	Price       pgtype.Numeric `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductName,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deliverOrder = `-- name: DeliverOrder :one
UPDATE orders SET status = 'delivered', updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, shop_id, status, total_amount, shipping_full_name, shipping_phone, shipping_province, shipping_district, shipping_ward, shipping_street, created_at, updated_at
`

func (q *Queries) DeliverOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, deliverOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopID,
		&i.Status,
		&i.TotalAmount,
		&i.ShippingFullName,
		&i.ShippingPhone,
		&i.ShippingProvince,
		&i.ShippingDistrict,
		&i.ShippingWard,
		&i.ShippingStreet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
  id, user_id, shop_id, status, total_amount, shipping_full_name, shipping_phone, shipping_province, shipping_district, shipping_ward, shipping_street, created_at, updated_at
FROM
  orders
WHERE
  id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopID,
		&i.Status,
		&i.TotalAmount,
		&i.ShippingFullName,
		&i.ShippingPhone,
		&i.ShippingProvince,
		&i.ShippingDistrict,
		&i.ShippingWard,
		&i.ShippingStreet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByShopID = `-- name: GetOrdersByShopID :many
SELECT
  id, user_id, shop_id, status, total_amount, shipping_full_name, shipping_phone, shipping_province, shipping_district, shipping_ward, shipping_street, created_at, updated_at
FROM
  orders
WHERE
  shop_id = $1
`

func (q *Queries) GetOrdersByShopID(ctx context.Context, shopID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByShopID, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShopID,
			&i.Status,
			&i.TotalAmount,
			&i.ShippingFullName,
			&i.ShippingPhone,
			&i.ShippingProvince,
			&i.ShippingDistrict,
			&i.ShippingWard,
			&i.ShippingStreet,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT
  id, user_id, shop_id, status, total_amount, shipping_full_name, shipping_phone, shipping_province, shipping_district, shipping_ward, shipping_street, created_at, updated_at
FROM
  orders
WHERE
  user_id = $1
`

func (q *Queries) GetOrdersByUserID(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShopID,
			&i.Status,
			&i.TotalAmount,
			&i.ShippingFullName,
			&i.ShippingPhone,
			&i.ShippingProvince,
			&i.ShippingDistrict,
			&i.ShippingWard,
			&i.ShippingStreet,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shipOrder = `-- name: ShipOrder :one
UPDATE orders SET status = 'shipping', updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, shop_id, status, total_amount, shipping_full_name, shipping_phone, shipping_province, shipping_district, shipping_ward, shipping_street, created_at, updated_at
`

func (q *Queries) ShipOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, shipOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopID,
		&i.Status,
		&i.TotalAmount,
		&i.ShippingFullName,
		&i.ShippingPhone,
		&i.ShippingProvince,
		&i.ShippingDistrict,
		&i.ShippingWard,
		&i.ShippingStreet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE
  orders
SET
  status = $2,
  updated_at = NOW()
WHERE
  id = $1 RETURNING id, user_id, shop_id, status, total_amount, shipping_full_name, shipping_phone, shipping_province, shipping_district, shipping_ward, shipping_street, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopID,
		&i.Status,
		&i.TotalAmount,
		&i.ShippingFullName,
		&i.ShippingPhone,
		&i.ShippingProvince,
		&i.ShippingDistrict,
		&i.ShippingWard,
		&i.ShippingStreet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
