// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox (id, event_type, payload)
VALUES ($1, $2, $3)
`

type CreateOutboxEventParams struct {
	ID        uuid.UUID `json:"id"`
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent, arg.ID, arg.EventType, arg.Payload)
	return err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, event_type, payload, status, created_at, processed_at FROM outbox
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT 10
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE outbox
SET status = 'processed', processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventProcessed, id)
	return err
}
