// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO
  products (id, shop_id, name, description)
VALUES
  ($1, $2, $3, $4) RETURNING id, shop_id, name, description, status, created_at, updated_at, stock, price
`

type CreateProductParams struct {
	ID          uuid.UUID   `json:"id"`
	ShopID      uuid.UUID   `json:"shop_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.ShopID,
		arg.Name,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Stock,
		&i.Price,
	)
	return i, err
}

const deductProductStock = `-- name: DeductProductStock :one
UPDATE
  products
SET
  stock = stock - $2,
  updated_at = NOW()
WHERE
  id = $1
  AND stock >= $2 RETURNING id, shop_id, name, description, status, created_at, updated_at, stock, price
`

type DeductProductStockParams struct {
	ID    uuid.UUID `json:"id"`
	Stock int32     `json:"stock"`
}

func (q *Queries) DeductProductStock(ctx context.Context, arg DeductProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, deductProductStock, arg.ID, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Stock,
		&i.Price,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE
  products
SET
  status = 'deleted',
  updated_at = NOW()
WHERE
  id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
  id, shop_id, name, description, status, created_at, updated_at, stock, price
FROM
  products
WHERE
  id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Stock,
		&i.Price,
	)
	return i, err
}

const getProductByIDAndShopOwner = `-- name: GetProductByIDAndShopOwner :one
SELECT
  p.id, p.shop_id, p.name, p.description, p.status, p.created_at, p.updated_at, p.stock, p.price
FROM
  products p
  JOIN shops s ON s.id = p.shop_id
WHERE
  p.id = $1
  AND s.owner_id = $2
`

type GetProductByIDAndShopOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetProductByIDAndShopOwner(ctx context.Context, arg GetProductByIDAndShopOwnerParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByIDAndShopOwner, arg.ID, arg.OwnerID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Stock,
		&i.Price,
	)
	return i, err
}

const getProductsByShopID = `-- name: GetProductsByShopID :many
SELECT
  id, shop_id, name, description, status, created_at, updated_at, stock, price
FROM
  products
WHERE
  shop_id = $1
  AND status = 'active'
`

func (q *Queries) GetProductsByShopID(ctx context.Context, shopID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByShopID, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Stock,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsForOrder = `-- name: GetProductsForOrder :many
SELECT
  id,
  name,
  price,
  stock,
  shop_id
FROM
  products
WHERE
  id = ANY($1::uuid[])
  AND shop_id = $2
  AND status = 'active'
ORDER BY
  id FOR
UPDATE
`

type GetProductsForOrderParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	ShopID  uuid.UUID   `json:"shop_id"`
}

type GetProductsForOrderRow struct {
	ID     uuid.UUID      `json:"id"`
	Name   string         `json:"name"`
	Price  pgtype.Numeric `json:"price"`
	Stock  int32          `json:"stock"`
	ShopID uuid.UUID      `json:"shop_id"`
}

func (q *Queries) GetProductsForOrder(ctx context.Context, arg GetProductsForOrderParams) ([]GetProductsForOrderRow, error) {
	rows, err := q.db.Query(ctx, getProductsForOrder, arg.Column1, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductsForOrderRow{}
	for rows.Next() {
		var i GetProductsForOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.ShopID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE
  products
SET
  name = $2,
  description = $3,
  status = $4,
  updated_at = NOW()
WHERE
  id = $1 RETURNING id, shop_id, name, description, status, created_at, updated_at, stock, price
`

type UpdateProductParams struct {
	ID          uuid.UUID     `json:"id"`
	Name        string        `json:"name"`
	Description pgtype.Text   `json:"description"`
	Status      ProductStatus `json:"status"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Stock,
		&i.Price,
	)
	return i, err
}
