// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO
  products (id, shop_id, name, description, price, stock)
VALUES
  ($1, $2, $3, $4, $5, $6) RETURNING id, shop_id, name, description, status, created_at, updated_at, stock, price, category_id, search_vector
`

type CreateProductParams struct {
	ID          uuid.UUID      `json:"id"`
	ShopID      uuid.UUID      `json:"shop_id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Stock       int32          `json:"stock"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.ShopID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Stock,
		&i.Price,
		&i.CategoryID,
		&i.SearchVector,
	)
	return i, err
}

const deductProductStock = `-- name: DeductProductStock :one
UPDATE
  products
SET
  stock = stock - $2,
  updated_at = NOW()
WHERE
  id = $1
  AND stock >= $2 RETURNING id, shop_id, name, description, status, created_at, updated_at, stock, price, category_id, search_vector
`

type DeductProductStockParams struct {
	ID    uuid.UUID `json:"id"`
	Stock int32     `json:"stock"`
}

func (q *Queries) DeductProductStock(ctx context.Context, arg DeductProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, deductProductStock, arg.ID, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Stock,
		&i.Price,
		&i.CategoryID,
		&i.SearchVector,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE
  products
SET
  status = 'deleted',
  updated_at = NOW()
WHERE
  id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT id, shop_id, name, description, status, created_at, updated_at, stock, price, category_id, search_vector FROM products
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Stock,
			&i.Price,
			&i.CategoryID,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT
  id, shop_id, name, description, status, created_at, updated_at, stock, price, category_id, search_vector
FROM
  products
WHERE
  id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Stock,
		&i.Price,
		&i.CategoryID,
		&i.SearchVector,
	)
	return i, err
}

const getProductByIDAndShopOwner = `-- name: GetProductByIDAndShopOwner :one
SELECT
  p.id, p.shop_id, p.name, p.description, p.status, p.created_at, p.updated_at, p.stock, p.price, p.category_id, p.search_vector
FROM
  products p
  JOIN shops s ON s.id = p.shop_id
WHERE
  p.id = $1
  AND s.owner_id = $2
`

type GetProductByIDAndShopOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetProductByIDAndShopOwner(ctx context.Context, arg GetProductByIDAndShopOwnerParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByIDAndShopOwner, arg.ID, arg.OwnerID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Stock,
		&i.Price,
		&i.CategoryID,
		&i.SearchVector,
	)
	return i, err
}

const getProductsByShopID = `-- name: GetProductsByShopID :many
SELECT
  id, shop_id, name, description, status, created_at, updated_at, stock, price, category_id, search_vector
FROM
  products
WHERE
  shop_id = $1
  AND status = 'active'
`

func (q *Queries) GetProductsByShopID(ctx context.Context, shopID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByShopID, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Stock,
			&i.Price,
			&i.CategoryID,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsForOrder = `-- name: GetProductsForOrder :many
SELECT
  id,
  name,
  price,
  stock,
  shop_id
FROM
  products
WHERE
  id = ANY($1::uuid[])
  AND shop_id = $2
  AND status = 'active'
ORDER BY
  id FOR
UPDATE
`

type GetProductsForOrderParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	ShopID  uuid.UUID   `json:"shop_id"`
}

type GetProductsForOrderRow struct {
	ID     uuid.UUID      `json:"id"`
	Name   string         `json:"name"`
	Price  pgtype.Numeric `json:"price"`
	Stock  int32          `json:"stock"`
	ShopID uuid.UUID      `json:"shop_id"`
}

func (q *Queries) GetProductsForOrder(ctx context.Context, arg GetProductsForOrderParams) ([]GetProductsForOrderRow, error) {
	rows, err := q.db.Query(ctx, getProductsForOrder, arg.Column1, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductsForOrderRow{}
	for rows.Next() {
		var i GetProductsForOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.ShopID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProductStock = `-- name: RestoreProductStock :exec
UPDATE products
SET
  stock = stock + $2,
  updated_at = NOW()
WHERE id = $1
`

type RestoreProductStockParams struct {
	ID    uuid.UUID `json:"id"`
	Stock int32     `json:"stock"`
}

func (q *Queries) RestoreProductStock(ctx context.Context, arg RestoreProductStockParams) error {
	_, err := q.db.Exec(ctx, restoreProductStock, arg.ID, arg.Stock)
	return err
}

const searchProducts = `-- name: SearchProducts :many
SELECT
  p.id,
  p.shop_id,
  p.category_id,
  p.name,
  p.description,
  p.price,
  p.stock,
  p.status,
  p.created_at,
  p.updated_at,
  s.name AS shop_name,
  c.name AS category_name
FROM products p
JOIN shops s ON p.shop_id = s.id
LEFT JOIN categories c ON p.category_id = c.id
WHERE p.status = 'active'
  AND ($1::text = '' OR p.search_vector @@ plainto_tsquery('english', $1))
  AND ($2::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR p.category_id = $2)
  AND ($3::numeric = 0 OR p.price >= $3)
  AND ($4::numeric = 0 OR p.price <= $4)
  AND ($5::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR p.id < $5)
ORDER BY p.id DESC
LIMIT $6
`

type SearchProductsParams struct {
	Column1 string         `json:"column_1"`
	Column2 uuid.UUID      `json:"column_2"`
	Column3 pgtype.Numeric `json:"column_3"`
	Column4 pgtype.Numeric `json:"column_4"`
	Column5 uuid.UUID      `json:"column_5"`
	Limit   int32          `json:"limit"`
}

type SearchProductsRow struct {
	ID           uuid.UUID          `json:"id"`
	ShopID       uuid.UUID          `json:"shop_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Price        pgtype.Numeric     `json:"price"`
	Stock        int32              `json:"stock"`
	Status       ProductStatus      `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ShopName     string             `json:"shop_name"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductsRow{}
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShopName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE
  products
SET
  name = $2,
  description = $3,
  status = $4,
  updated_at = NOW()
WHERE
  id = $1 RETURNING id, shop_id, name, description, status, created_at, updated_at, stock, price, category_id, search_vector
`

type UpdateProductParams struct {
	ID          uuid.UUID     `json:"id"`
	Name        string        `json:"name"`
	Description pgtype.Text   `json:"description"`
	Status      ProductStatus `json:"status"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Stock,
		&i.Price,
		&i.CategoryID,
		&i.SearchVector,
	)
	return i, err
}
