// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelOrder(ctx context.Context, id uuid.UUID) (Order, error)
	CheckUserEmailExists(ctx context.Context, email pgtype.Text) (bool, error)
	CheckUserEnabledMFA(ctx context.Context, userID uuid.UUID) (bool, error)
	CheckUserPhoneExists(ctx context.Context, phone pgtype.Text) (bool, error)
	ConfirmOrder(ctx context.Context, id uuid.UUID) (Order, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAuth(ctx context.Context, arg CreateUserAuthParams) (UserAuth, error)
	CreateUserMFA(ctx context.Context, arg CreateUserMFAParams) (UserMfa, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (AuthSession, error)
	DeductProductStock(ctx context.Context, arg DeductProductStockParams) (Product, error)
	DeleteAddress(ctx context.Context, id uuid.UUID) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteSessionByRefreshToken(ctx context.Context, refreshTokenHash string) error
	DeliverOrder(ctx context.Context, id uuid.UUID) (Order, error)
	EnableUserMFA(ctx context.Context, userID uuid.UUID) error
	GeShopByID(ctx context.Context, id uuid.UUID) (Shop, error)
	GetAddressByID(ctx context.Context, id uuid.UUID) (Address, error)
	GetAddressesByUserID(ctx context.Context, userID uuid.UUID) (Address, error)
	GetAllProducts(ctx context.Context) ([]Product, error)
	GetCategories(ctx context.Context) ([]Category, error)
	GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	GetOrderItemsByOrderIDs(ctx context.Context, orderIds []uuid.UUID) ([]OrderItem, error)
	GetOrdersByShopID(ctx context.Context, shopID uuid.UUID) ([]Order, error)
	GetOrdersByUserID(ctx context.Context, userID uuid.UUID) ([]Order, error)
	GetOrdersByUserIDWithCursor(ctx context.Context, arg GetOrdersByUserIDWithCursorParams) ([]Order, error)
	GetPendingOutboxEvents(ctx context.Context) ([]Outbox, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductByIDAndShopOwner(ctx context.Context, arg GetProductByIDAndShopOwnerParams) (Product, error)
	GetProductsByShopID(ctx context.Context, shopID uuid.UUID) ([]Product, error)
	GetProductsForOrder(ctx context.Context, arg GetProductsForOrderParams) ([]GetProductsForOrderRow, error)
	GetRevenueSummary(ctx context.Context, arg GetRevenueSummaryParams) ([]GetRevenueSummaryRow, error)
	GetReviewByOrderAndProduct(ctx context.Context, arg GetReviewByOrderAndProductParams) (Review, error)
	GetReviewsByProductID(ctx context.Context, arg GetReviewsByProductIDParams) ([]GetReviewsByProductIDRow, error)
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (AuthSession, error)
	GetShopByOwnerID(ctx context.Context, ownerID uuid.UUID) (Shop, error)
	GetShopBySlug(ctx context.Context, slug string) (Shop, error)
	GetSubcategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone pgtype.Text) (User, error)
	GetUserMFAByUserID(ctx context.Context, userID uuid.UUID) (UserMfa, error)
	GetUserPasswordHash(ctx context.Context, arg GetUserPasswordHashParams) (pgtype.Text, error)
	GetUserTOTPSecret(ctx context.Context, userID uuid.UUID) (string, error)
	MarkOutboxEventFailed(ctx context.Context, id uuid.UUID) error
	MarkOutboxEventProcessed(ctx context.Context, id uuid.UUID) error
	RestoreProductStock(ctx context.Context, arg RestoreProductStockParams) error
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	SetDefaultAddress(ctx context.Context, userID uuid.UUID) error
	ShipOrder(ctx context.Context, id uuid.UUID) (Order, error)
	UpdateAddressDefault(ctx context.Context, id uuid.UUID) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error)
	UpsertRevenueSummary(ctx context.Context, arg UpsertRevenueSummaryParams) error
}

var _ Querier = (*Queries)(nil)
