// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revenue.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRevenueSummary = `-- name: GetRevenueSummary :many
SELECT date, total, order_count
FROM revenue_summary
WHERE shop_id = $1
  AND ($2::date = '0001-01-01'::date OR date >= $2::date)
  AND ($3::date = '0001-01-01'::date OR date <= $3::date)
ORDER BY date DESC
`

type GetRevenueSummaryParams struct {
	ShopID   uuid.UUID   `json:"shop_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetRevenueSummaryRow struct {
	Date       pgtype.Date    `json:"date"`
	Total      pgtype.Numeric `json:"total"`
	OrderCount int32          `json:"order_count"`
}

func (q *Queries) GetRevenueSummary(ctx context.Context, arg GetRevenueSummaryParams) ([]GetRevenueSummaryRow, error) {
	rows, err := q.db.Query(ctx, getRevenueSummary, arg.ShopID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRevenueSummaryRow{}
	for rows.Next() {
		var i GetRevenueSummaryRow
		if err := rows.Scan(&i.Date, &i.Total, &i.OrderCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRevenueSummary = `-- name: UpsertRevenueSummary :exec
INSERT INTO revenue_summary (shop_id, date, total, order_count)
VALUES ($1, $2, $3, 1)
ON CONFLICT (shop_id, date)
DO UPDATE SET
  total = revenue_summary.total + EXCLUDED.total,
  order_count = revenue_summary.order_count + 1
`

type UpsertRevenueSummaryParams struct {
	ShopID uuid.UUID      `json:"shop_id"`
	Date   pgtype.Date    `json:"date"`
	Total  pgtype.Numeric `json:"total"`
}

func (q *Queries) UpsertRevenueSummary(ctx context.Context, arg UpsertRevenueSummaryParams) error {
	_, err := q.db.Exec(ctx, upsertRevenueSummary, arg.ShopID, arg.Date, arg.Total)
	return err
}
