// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (id, order_id, product_id, user_id, rating, comment)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, product_id, user_id, rating, comment, created_at
`

type CreateReviewParams struct {
	ID        uuid.UUID   `json:"id"`
	OrderID   uuid.UUID   `json:"order_id"`
	ProductID uuid.UUID   `json:"product_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Rating    int32       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewByOrderAndProduct = `-- name: GetReviewByOrderAndProduct :one
SELECT id, order_id, product_id, user_id, rating, comment, created_at FROM reviews
WHERE order_id = $1 AND product_id = $2
`

type GetReviewByOrderAndProductParams struct {
	OrderID   uuid.UUID `json:"order_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) GetReviewByOrderAndProduct(ctx context.Context, arg GetReviewByOrderAndProductParams) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByOrderAndProduct, arg.OrderID, arg.ProductID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewsByProductID = `-- name: GetReviewsByProductID :many
SELECT r.id, r.order_id, r.product_id, r.user_id, r.rating, r.comment, r.created_at, u.full_name as user_name
FROM reviews r
JOIN users u ON r.user_id = u.id
WHERE r.product_id = $1
  AND ($2::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR r.id < $2)
ORDER BY r.id DESC
LIMIT $3
`

type GetReviewsByProductIDParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Column2   uuid.UUID `json:"column_2"`
	Limit     int32     `json:"limit"`
}

type GetReviewsByProductIDRow struct {
	ID        uuid.UUID          `json:"id"`
	OrderID   uuid.UUID          `json:"order_id"`
	ProductID uuid.UUID          `json:"product_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Rating    int32              `json:"rating"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserName  string             `json:"user_name"`
}

func (q *Queries) GetReviewsByProductID(ctx context.Context, arg GetReviewsByProductIDParams) ([]GetReviewsByProductIDRow, error) {
	rows, err := q.db.Query(ctx, getReviewsByProductID, arg.ProductID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewsByProductIDRow{}
	for rows.Next() {
		var i GetReviewsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
