// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shop.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShop = `-- name: CreateShop :one
INSERT INTO
  shops (id, owner_id, name, slug, description, logo_url)
VALUES
  ($1, $2, $3, $4, $5, $6) RETURNING id, owner_id, name, slug, description, logo_url, status, created_at, updated_at
`

type CreateShopParams struct {
	ID          uuid.UUID   `json:"id"`
	OwnerID     uuid.UUID   `json:"owner_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, createShop,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LogoUrl,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const geShopByID = `-- name: GeShopByID :one
SELECT
  id, owner_id, name, slug, description, logo_url, status, created_at, updated_at
FROM
  shops
WHERE
  id = $1
`

func (q *Queries) GeShopByID(ctx context.Context, id uuid.UUID) (Shop, error) {
	row := q.db.QueryRow(ctx, geShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopByOwnerID = `-- name: GetShopByOwnerID :one
SELECT
  id, owner_id, name, slug, description, logo_url, status, created_at, updated_at
FROM
  shops
WHERE
  owner_id = $1
`

func (q *Queries) GetShopByOwnerID(ctx context.Context, ownerID uuid.UUID) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByOwnerID, ownerID)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopBySlug = `-- name: GetShopBySlug :one
SELECT
  id, owner_id, name, slug, description, logo_url, status, created_at, updated_at
FROM
  shops
WHERE
  slug = $1
`

func (q *Queries) GetShopBySlug(ctx context.Context, slug string) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopBySlug, slug)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShop = `-- name: UpdateShop :one
UPDATE
  shops
SET
  name = $2,
  description = $3,
  logo_url = $4,
  updated_at = NOW()
WHERE
  id = $1 RETURNING id, owner_id, name, slug, description, logo_url, status, created_at, updated_at
`

type UpdateShopParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, updateShop,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
