// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_sessions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO
  auth_sessions (
    id,
    user_id,
    ip,
    user_agent,
    refresh_token_hash,
    expires_at,
    is_remember
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, ip, user_agent, refresh_token_hash, expires_at, is_remember, created_at, updated_at, deleted_at
`

type CreateUserSessionParams struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Ip               pgtype.Text        `json:"ip"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	IsRemember       bool               `json:"is_remember"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.ID,
		arg.UserID,
		arg.Ip,
		arg.UserAgent,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.IsRemember,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Ip,
		&i.UserAgent,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.IsRemember,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSessionByRefreshToken = `-- name: DeleteSessionByRefreshToken :exec
DELETE FROM auth_sessions WHERE refresh_token_hash = $1
`

func (q *Queries) DeleteSessionByRefreshToken(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByRefreshToken, refreshTokenHash)
	return err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, ip, user_agent, refresh_token_hash, expires_at, is_remember, created_at, updated_at, deleted_at FROM auth_sessions WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Ip,
		&i.UserAgent,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.IsRemember,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
