// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserEmailExists = `-- name: CheckUserEmailExists :one
SELECT
  EXISTS(
    SELECT
      1
    FROM
      users
    WHERE
      email = $1
  )
`

func (q *Queries) CheckUserEmailExists(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUserPhoneExists = `-- name: CheckUserPhoneExists :one
SELECT
  EXISTS(
    SELECT
      1
    FROM
      users
    WHERE
      phone = $1
  )
`

func (q *Queries) CheckUserPhoneExists(ctx context.Context, phone pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserPhoneExists, phone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (id, full_name, email, phone)
VALUES
  ($1, $2, $3, $4) RETURNING id, full_name, email, phone, status, created_at, updated_at
`

type CreateUserParams struct {
	ID       uuid.UUID   `json:"id"`
	FullName string      `json:"full_name"`
	Email    pgtype.Text `json:"email"`
	Phone    pgtype.Text `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
