// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_mfa.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const checkUserEnabledMFA = `-- name: CheckUserEnabledMFA :one
SELECT
  EXISTS(
    SELECT
      1
    FROM
      user_mfa
    WHERE
      user_id = $1
      AND is_enabled = true
  )
`

func (q *Queries) CheckUserEnabledMFA(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserEnabledMFA, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUserMFA = `-- name: CreateUserMFA :one
INSERT INTO user_mfa (id, user_id, method, secret_key)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, method, secret_key, backup_codes, is_enabled, created_at, updated_at
`

type CreateUserMFAParams struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Method    MethodType `json:"method"`
	SecretKey string     `json:"secret_key"`
}

func (q *Queries) CreateUserMFA(ctx context.Context, arg CreateUserMFAParams) (UserMfa, error) {
	row := q.db.QueryRow(ctx, createUserMFA,
		arg.ID,
		arg.UserID,
		arg.Method,
		arg.SecretKey,
	)
	var i UserMfa
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.SecretKey,
		&i.BackupCodes,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enableUserMFA = `-- name: EnableUserMFA :exec
UPDATE user_mfa SET is_enabled = true WHERE user_id = $1 AND method = 'totp'
`

func (q *Queries) EnableUserMFA(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableUserMFA, userID)
	return err
}

const getUserMFAByUserID = `-- name: GetUserMFAByUserID :one
SELECT id, user_id, method, secret_key, backup_codes, is_enabled, created_at, updated_at FROM user_mfa WHERE user_id = $1 AND method ='totp'
`

func (q *Queries) GetUserMFAByUserID(ctx context.Context, userID uuid.UUID) (UserMfa, error) {
	row := q.db.QueryRow(ctx, getUserMFAByUserID, userID)
	var i UserMfa
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.SecretKey,
		&i.BackupCodes,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTOTPSecret = `-- name: GetUserTOTPSecret :one
SELECT secret_key FROM user_mfa WHERE user_id = $1 AND method = 'totp' AND is_enabled = true
`

func (q *Queries) GetUserTOTPSecret(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserTOTPSecret, userID)
	var secret_key string
	err := row.Scan(&secret_key)
	return secret_key, err
}
