// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_auth.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserAuth = `-- name: CreateUserAuth :one
INSERT INTO
  user_auth (user_id, provider, password_hash)
VALUES
  ($1, $2, $3) RETURNING user_id, provider, provider_id, password_hash, is_verified, created_at, updated_at, deleted_at
`

type CreateUserAuthParams struct {
	UserID       uuid.UUID    `json:"user_id"`
	Provider     ProviderType `json:"provider"`
	PasswordHash pgtype.Text  `json:"password_hash"`
}

func (q *Queries) CreateUserAuth(ctx context.Context, arg CreateUserAuthParams) (UserAuth, error) {
	row := q.db.QueryRow(ctx, createUserAuth, arg.UserID, arg.Provider, arg.PasswordHash)
	var i UserAuth
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
